/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 */

plugins {
    id("eclipse")                                                               
    id("application")
}

repositories {                                                          
    mavenCentral()
}

dependencies {                                                          
}

application {                                                           
    mainClass = "YAVC.Main.Main"
}

tasks.jar {
  manifest {
    attributes(mapOf("Main-Class" to application.mainClass))
  }
}

sourceSets {
    main {
        java {
	   srcDir("src")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
